import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SearchBar from '../components/Home/SearchBar/index'
import FilterPanel from '../components/Home/FilterPanel/index'
import List from '../components/Home/List/index'
import React,{useState} from 'react'
export default function Home() {
  const [value,setValue]=useState('')
  const [selectedCategory,setSelectedCategory]=useState(null)
  const handlerChange=()=>{

  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <SearchBar handlerChange={handlerChange} value={value}/>
       <div className="flex gap-5 px-2 py-2">
       <FilterPanel/>
       <List/>
       </div>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
